### ISSUE TITLE
Cannot Log in

### ISSUE THREAD

**Issue by BruceBevens** [AllanOricil/SOQL-Editor-Issues#20]
Hi Allan!

Is there a way to bypass the log in? I am working with my network team but recently the outbound to your site is being blocked so I cannot log in :(

just wondering if there is a temporary work around until my network team gets back to me. 

Thank You, 
Bruce

**Comment by AllanOricil** [comment]
Hi @BruceBevens . The app won't work if you dont have internet. The login/signup is just so I can have your e-mails registered in case you guys decide to buy a license to help me to maintain the app and delivery more value. But after loging in into the app, you need internet to do requests to salesforce. Can you show what happens when you open the app?

**Comment by BruceBevens** [comment]
Hi Allan,

The block is just to your site currently, it just will not connect to https://salesforcequeryeditor.com/. It is definitely a block on our side, besides that the internet works just fine.

Thank You,

Bruce Bevens | Database Administrator II

o 949 509 2502 | m 949 351 6912


This e-mail, including any accompanying attachments, may contain confidential information that is private, personal, and/or proprietary, and it is for the sole use of the intended recipient(s). Any unauthorized review, use, distribution or disclosure by others is strictly prohibited. If you have received this document in error, please immediately contact Bruce Bevens and delete all copies of this message.

**Comment by AllanOricil** [comment]
@BruceBevens use the app inside vscode. I think you won't have a problem there
